// Bollywood movies data with release date and genre
export const bollywoodMovies = [
  { name: "Dilwale Dulhania Le Jayenge", year: 1995, genres: ["Romance", "Drama", "Comedy"] },
  { name: "3 Idiots", year: 2009, genres: ["Comedy", "Drama"] },
  { name: "Lagaan", year: 2001, genres: ["Drama", "Sports", "Musical"] },
  { name: "Sholay", year: 1975, genres: ["Action", "Adventure", "Drama"] },
  { name: "Dangal", year: 2016, genres: ["Biographical", "Sports", "Drama"] },
  { name: "PK", year: 2014, genres: ["Comedy", "Drama", "Sci-Fi"] },
  { name: "Bajrangi Bhaijaan", year: 2015, genres: ["Action", "Comedy", "Drama"] },
  { name: "Sultan", year: 2016, genres: ["Sports", "Action", "Drama"] },
  { name: "Padmaavat", year: 2018, genres: ["Drama", "Historical", "Epic"] },
  { name: "Sanju", year: 2018, genres: ["Biographical", "Drama"] },
  { name: "Tiger Zinda Hai", year: 2017, genres: ["Action", "Thriller"] },
  { name: "War", year: 2019, genres: ["Action", "Thriller"] },
  { name: "Kabir Singh", year: 2019, genres: ["Romance", "Drama"] },
  { name: "Good Newwz", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Tanhaji", year: 2020, genres: ["Action", "Historical", "Drama"] },
  { name: "Baaghi 3", year: 2020, genres: ["Action", "Thriller"] },
  { name: "Sooryavanshi", year: 2021, genres: ["Action", "Thriller"] },
  { name: "83", year: 2021, genres: ["Sports", "Drama", "Biographical"] },
  { name: "Gangubai Kathiawadi", year: 2022, genres: ["Biographical", "Drama"] },
  { name: "RRR", year: 2022, genres: ["Action", "Drama", "Epic"] },
  { name: "Brahmastra", year: 2022, genres: ["Action", "Fantasy", "Adventure"] },
  { name: "Pathaan", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Jawan", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Animal", year: 2023, genres: ["Action", "Crime", "Drama"] },
  { name: "Gadar 2", year: 2023, genres: ["Action", "Drama", "Historical"] },
  { name: "KGF: Chapter 2", year: 2022, genres: ["Action", "Crime", "Thriller"] },
  { name: "Pushpa: The Rise", year: 2021, genres: ["Action", "Crime", "Drama"] },
  { name: "Bahubali 2: The Conclusion", year: 2017, genres: ["Action", "Drama", "Epic"] },
  { name: "Bahubali: The Beginning", year: 2015, genres: ["Action", "Drama", "Epic"] },
  { name: "Queen", year: 2013, genres: ["Comedy", "Drama"] },
  { name: "Zindagi Na Milegi Dobara", year: 2011, genres: ["Comedy", "Drama"] },
  { name: "Yeh Jawaani Hai Deewani", year: 2013, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Barfi!", year: 2012, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Gully Boy", year: 2019, genres: ["Musical", "Drama"] },
  { name: "Andhadhun", year: 2018, genres: ["Thriller", "Comedy", "Crime"] },
  { name: "Stree", year: 2018, genres: ["Horror", "Comedy"] },
  { name: "Badhaai Ho", year: 2018, genres: ["Comedy", "Drama"] },
  { name: "Uri: The Surgical Strike", year: 2019, genres: ["Action", "War", "Drama"] },
  { name: "Kesari", year: 2019, genres: ["Action", "War", "Historical"] },
  { name: "Chhichhore", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Dream Girl", year: 2019, genres: ["Comedy", "Romance"] },
  { name: "Housefull 4", year: 2019, genres: ["Comedy"] },
  { name: "Total Dhamaal", year: 2019, genres: ["Comedy", "Adventure"] },
  { name: "Mission Mangal", year: 2019, genres: ["Drama", "Sci-Fi"] },
  { name: "Saaho", year: 2019, genres: ["Action", "Thriller"] },
  { name: "Bharat", year: 2019, genres: ["Drama", "Action"] },
  { name: "Super 30", year: 2019, genres: ["Biographical", "Drama"] },
  { name: "The Sky Is Pink", year: 2019, genres: ["Biographical", "Drama"] },
  { name: "Made in China", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Ujda Chaman", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Bala", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Marjaavaan", year: 2019, genres: ["Action", "Romance", "Drama"] },
  { name: "Pati Patni Aur Woh", year: 2019, genres: ["Comedy", "Romance"] },
  { name: "Good Newwz", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Tanhaji: The Unsung Warrior", year: 2020, genres: ["Action", "Historical", "Drama"] },
  { name: "Street Dancer 3D", year: 2020, genres: ["Musical", "Dance", "Drama"] },
  { name: "Panga", year: 2020, genres: ["Sports", "Drama"] },
  { name: "Malang", year: 2020, genres: ["Action", "Thriller", "Romance"] },
  { name: "Shubh Mangal Zyada Saavdhan", year: 2020, genres: ["Comedy", "Romance"] },
  { name: "Baaghi 3", year: 2020, genres: ["Action", "Thriller"] },
  { name: "Angrezi Medium", year: 2020, genres: ["Comedy", "Drama"] },
  { name: "Thappad", year: 2020, genres: ["Drama"] },
  { name: "Lootcase", year: 2020, genres: ["Comedy", "Crime"] },
  { name: "Gunjan Saxena", year: 2020, genres: ["Biographical", "Drama", "War"] },
  { name: "Sadak 2", year: 2020, genres: ["Thriller", "Drama"] },
  { name: "Coolie No. 1", year: 2020, genres: ["Comedy"] },
  { name: "Indoo Ki Jawani", year: 2020, genres: ["Comedy", "Romance"] },
  { name: "Shakuntala Devi", year: 2020, genres: ["Biographical", "Drama"] },
  { name: "Dil Bechara", year: 2020, genres: ["Romance", "Drama"] },
  { name: "Laxmii", year: 2020, genres: ["Horror", "Comedy"] },
  { name: "Atrangi Re", year: 2021, genres: ["Romance", "Drama", "Musical"] },
  { name: "Shershaah", year: 2021, genres: ["Biographical", "War", "Drama"] },
  { name: "Sardar Udham", year: 2021, genres: ["Biographical", "Historical", "Drama"] },
  { name: "Sooryavanshi", year: 2021, genres: ["Action", "Thriller"] },
  { name: "Antim: The Final Truth", year: 2021, genres: ["Action", "Crime", "Drama"] },
  { name: "Bunty Aur Babli 2", year: 2021, genres: ["Comedy", "Action", "Crime"] },
  { name: "Satyameva Jayate 2", year: 2021, genres: ["Action", "Thriller"] },
  { name: "83", year: 2021, genres: ["Sports", "Drama", "Biographical"] },
  { name: "Pushpa: The Rise", year: 2021, genres: ["Action", "Crime", "Drama"] },
  { name: "Radhe", year: 2021, genres: ["Action", "Thriller"] },
  { name: "Bhool Bhulaiyaa 2", year: 2022, genres: ["Horror", "Comedy", "Thriller"] },
  { name: "Kashmir Files", year: 2022, genres: ["Drama", "Thriller"] },
  { name: "Gangubai Kathiawadi", year: 2022, genres: ["Biographical", "Drama"] },
  { name: "Bachchhan Paandey", year: 2022, genres: ["Action", "Comedy"] },
  { name: "RRR", year: 2022, genres: ["Action", "Drama", "Epic"] },
  { name: "KGF: Chapter 2", year: 2022, genres: ["Action", "Crime", "Thriller"] },
  { name: "Heropanti 2", year: 2022, genres: ["Action", "Thriller"] },
  { name: "Runway 34", year: 2022, genres: ["Thriller", "Drama"] },
  { name: "Dhaakad", year: 2022, genres: ["Action", "Thriller"] },
  { name: "Samrat Prithviraj", year: 2022, genres: ["Action", "Historical", "Drama"] },
  { name: "Vikram", year: 2022, genres: ["Action", "Thriller"] },
  { name: "Brahmastra", year: 2022, genres: ["Action", "Fantasy", "Adventure"] },
  { name: "Vikram Vedha", year: 2022, genres: ["Action", "Crime", "Thriller"] },
  { name: "Ram Setu", year: 2022, genres: ["Action", "Adventure", "Mystery"] },
  { name: "Drishyam 2", year: 2022, genres: ["Thriller", "Crime", "Drama"] },
  { name: "Cirkus", year: 2022, genres: ["Comedy"] },
  { name: "Pathaan", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Tu Jhoothi Main Makkaar", year: 2023, genres: ["Romance", "Comedy"] },
  { name: "Bholaa", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Kisi Ka Bhai Kisi Ki Jaan", year: 2023, genres: ["Action", "Comedy", "Drama"] },
  { name: "The Kerala Story", year: 2023, genres: ["Drama"] },
  { name: "Zara Hatke Zara Bachke", year: 2023, genres: ["Romance", "Comedy"] },
  { name: "Adipurush", year: 2023, genres: ["Action", "Fantasy", "Epic"] },
  { name: "Satyaprem Ki Katha", year: 2023, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Rocky Aur Rani Kii Prem Kahaani", year: 2023, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Gadar 2", year: 2023, genres: ["Action", "Drama", "Historical"] },
  { name: "OMG 2", year: 2023, genres: ["Comedy", "Drama"] },
  { name: "Dream Girl 2", year: 2023, genres: ["Comedy", "Romance"] },
  { name: "Jawan", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Fukrey 3", year: 2023, genres: ["Comedy"] },
  { name: "Mission Raniganj", year: 2023, genres: ["Biographical", "Drama", "Thriller"] },
  { name: "Ganpath", year: 2023, genres: ["Action", "Sci-Fi"] },
  { name: "Tiger 3", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Animal", year: 2023, genres: ["Action", "Crime", "Drama"] },
  { name: "Sam Bahadur", year: 2023, genres: ["Biographical", "War", "Drama"] },
  { name: "Dunki", year: 2023, genres: ["Comedy", "Drama"] },
  { name: "Salaar", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Amar Singh Chamkila", year: 2024, genres: ["Biographical", "Musical", "Drama"] },
  { name: "Crew", year: 2024, genres: ["Comedy", "Crime"] },
  { name: "Bade Miyan Chote Miyan", year: 2024, genres: ["Action", "Comedy"] },
  { name: "Maidaan", year: 2024, genres: ["Sports", "Biographical", "Drama"] },
  { name: "Chandu Champion", year: 2024, genres: ["Biographical", "Sports", "Drama"] },
  { name: "Kalki 2898 AD", year: 2024, genres: ["Sci-Fi", "Action", "Fantasy"] },
  { name: "Singham Again", year: 2024, genres: ["Action", "Thriller"] },
  { name: "Stree 2", year: 2024, genres: ["Horror", "Comedy"] },
  { name: "Welcome To The Jungle", year: 2024, genres: ["Comedy", "Adventure"] },
  { name: "Fighter", year: 2024, genres: ["Action", "Drama", "War"] },
  { name: "Teri Baaton Mein Aisa Uljha Jiya", year: 2024, genres: ["Romance", "Comedy", "Sci-Fi"] },
  { name: "Shaitaan", year: 2024, genres: ["Horror", "Thriller"] },
  { name: "Article 370", year: 2024, genres: ["Action", "Thriller", "Political"] },
  { name: "Yodha", year: 2024, genres: ["Action", "Thriller"] },
  { name: "Bastar: The Naxal Story", year: 2024, genres: ["Action", "Thriller", "Political"] },
  { name: "Swatantrya Veer Savarkar", year: 2024, genres: ["Biographical", "Historical", "Drama"] },
  { name: "Madgaon Express", year: 2024, genres: ["Comedy"] },
  { name: "Ruslaan", year: 2024, genres: ["Action", "Thriller"] },
  { name: "Srikanth", year: 2024, genres: ["Biographical", "Drama"] },
  { name: "Mr. & Mrs. Mahi", year: 2024, genres: ["Romance", "Sports", "Drama"] },
  { name: "Munjya", year: 2024, genres: ["Horror", "Comedy"] },
  { name: "Ishq Vishk Rebound", year: 2024, genres: ["Romance", "Comedy"] },
  { name: "Kill", year: 2024, genres: ["Action", "Thriller"] },
  { name: "Sarfira", year: 2024, genres: ["Drama", "Biographical"] },
  { name: "Bad Newz", year: 2024, genres: ["Comedy", "Drama"] },
  { name: "Khel Khel Mein", year: 2024, genres: ["Comedy", "Drama"] },
  { name: "Do Aur Do Pyaar", year: 2024, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Amar Prem", year: 1972, genres: ["Romance", "Drama"] },
  { name: "Deewaar", year: 1975, genres: ["Action", "Crime", "Drama"] },
  { name: "Zanjeer", year: 1973, genres: ["Action", "Crime", "Drama"] },
  { name: "Don", year: 1978, genres: ["Action", "Crime", "Thriller"] },
  { name: "Trishul", year: 1978, genres: ["Action", "Drama"] },
  { name: "Kaala Patthar", year: 1979, genres: ["Drama"] },
  { name: "Mr. India", year: 1987, genres: ["Sci-Fi", "Comedy", "Action"] },
  { name: "Qayamat Se Qayamat Tak", year: 1988, genres: ["Romance", "Musical", "Drama"] },
  { name: "Maine Pyar Kiya", year: 1989, genres: ["Romance", "Musical", "Drama"] },
  { name: "Hum Aapke Hain Koun..!", year: 1994, genres: ["Romance", "Musical", "Drama"] },
  { name: "Kuch Kuch Hota Hai", year: 1998, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Mohabbatein", year: 2000, genres: ["Romance", "Musical", "Drama"] },
  { name: "Kabhi Khushi Kabhie Gham", year: 2001, genres: ["Romance", "Drama", "Musical"] },
  { name: "Kal Ho Naa Ho", year: 2003, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Veer-Zaara", year: 2004, genres: ["Romance", "Drama", "Musical"] },
  { name: "Swades", year: 2004, genres: ["Drama"] },
  { name: "Black", year: 2005, genres: ["Drama"] },
  { name: "Rang De Basanti", year: 2006, genres: ["Drama", "Comedy"] },
  { name: "Chak De! India", year: 2007, genres: ["Sports", "Drama"] },
  { name: "Taare Zameen Par", year: 2007, genres: ["Drama", "Family"] },
  { name: "Jodhaa Akbar", year: 2008, genres: ["Romance", "Historical", "Drama"] },
  { name: "Ghajini", year: 2008, genres: ["Action", "Thriller", "Romance"] },
  { name: "Wake Up Sid", year: 2009, genres: ["Romance", "Comedy", "Drama"] },
  { name: "My Name Is Khan", year: 2010, genres: ["Drama"] },
  { name: "Once Upon a Time in Mumbai", year: 2010, genres: ["Crime", "Drama"] },
  { name: "Band Baaja Baaraat", year: 2010, genres: ["Romance", "Comedy"] },
  { name: "Don 2", year: 2011, genres: ["Action", "Crime", "Thriller"] },
  { name: "Ra.One", year: 2011, genres: ["Action", "Sci-Fi", "Superhero"] },
  { name: "Agneepath", year: 2012, genres: ["Action", "Crime", "Drama"] },
  { name: "Ek Tha Tiger", year: 2012, genres: ["Action", "Romance", "Thriller"] },
  { name: "Jab Tak Hai Jaan", year: 2012, genres: ["Romance", "Drama"] },
  { name: "Chennai Express", year: 2013, genres: ["Action", "Comedy", "Romance"] },
  { name: "Krrish 3", year: 2013, genres: ["Action", "Sci-Fi", "Superhero"] },
  { name: "Dhoom 3", year: 2013, genres: ["Action", "Crime", "Thriller"] },
  { name: "Happy New Year", year: 2014, genres: ["Action", "Comedy", "Heist"] },
  { name: "Kick", year: 2014, genres: ["Action", "Comedy", "Thriller"] },
  { name: "Haider", year: 2014, genres: ["Drama", "Thriller"] },
  { name: "2 States", year: 2014, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Bang Bang!", year: 2014, genres: ["Action", "Romance", "Thriller"] },
  { name: "Happy Ending", year: 2014, genres: ["Romance", "Comedy"] },
  { name: "Roy", year: 2015, genres: ["Romance", "Thriller", "Drama"] },
  { name: "Dilwale", year: 2015, genres: ["Action", "Comedy", "Romance"] },
  { name: "Tamasha", year: 2015, genres: ["Romance", "Drama"] },
  { name: "Airlift", year: 2016, genres: ["Drama", "Thriller"] },
  { name: "Rustom", year: 2016, genres: ["Thriller", "Drama"] },
  { name: "Ae Dil Hai Mushkil", year: 2016, genres: ["Romance", "Musical", "Drama"] },
  { name: "Dear Zindagi", year: 2016, genres: ["Drama", "Romance"] },
  { name: "Raees", year: 2017, genres: ["Action", "Crime", "Drama"] },
  { name: "Toilet: Ek Prem Katha", year: 2017, genres: ["Comedy", "Drama"] },
  { name: "Judwaa 2", year: 2017, genres: ["Comedy", "Action"] },
  { name: "Golmaal Again", year: 2017, genres: ["Comedy", "Horror"] },
  { name: "Pad Man", year: 2018, genres: ["Biographical", "Drama", "Comedy"] },
  { name: "Raazi", year: 2018, genres: ["Spy", "Thriller", "Drama"] },
  { name: "Simmba", year: 2018, genres: ["Action", "Comedy", "Crime"] },
  { name: "Zero", year: 2018, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Thugs of Hindostan", year: 2018, genres: ["Action", "Adventure", "Drama"] },
  { name: "2.0", year: 2018, genres: ["Action", "Sci-Fi", "Thriller"] },
  { name: "Kedarnath", year: 2018, genres: ["Romance", "Drama"] },
  { name: "Manikarnika", year: 2019, genres: ["Biographical", "Historical", "Drama"] },
  { name: "Kalank", year: 2019, genres: ["Romance", "Drama", "Musical"] },
  { name: "Student of the Year 2", year: 2019, genres: ["Romance", "Comedy", "Drama"] },
  { name: "India's Most Wanted", year: 2019, genres: ["Action", "Thriller"] },
  { name: "Article 15", year: 2019, genres: ["Crime", "Drama", "Thriller"] },
  { name: "Batla House", year: 2019, genres: ["Action", "Thriller", "Drama"] },
  { name: "Saand Ki Aankh", year: 2019, genres: ["Biographical", "Drama"] },
  { name: "Made in Heaven", year: 2019, genres: ["Drama"] },
  { name: "The Zoya Factor", year: 2019, genres: ["Romance", "Comedy"] },
  { name: "Prassthanam", year: 2019, genres: ["Action", "Crime", "Drama"] },
  { name: "Section 375", year: 2019, genres: ["Crime", "Drama", "Thriller"] },
  { name: "War", year: 2019, genres: ["Action", "Thriller"] },
  { name: "Laal Kaptaan", year: 2019, genres: ["Action", "Drama", "Western"] },
  { name: "Housefull 4", year: 2019, genres: ["Comedy"] },
  { name: "Made in China", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Saand Ki Aankh", year: 2019, genres: ["Biographical", "Drama"] },
  { name: "Ujda Chaman", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Bala", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Pati Patni Aur Woh", year: 2019, genres: ["Comedy", "Romance"] },
  { name: "Good Newwz", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Dabangg 3", year: 2019, genres: ["Action", "Comedy", "Crime"] },
  { name: "Panga", year: 2020, genres: ["Sports", "Drama"] },
  { name: "Malang", year: 2020, genres: ["Action", "Thriller", "Romance"] },
  { name: "Shubh Mangal Zyada Saavdhan", year: 2020, genres: ["Comedy", "Romance"] },
  { name: "Baaghi 3", year: 2020, genres: ["Action", "Thriller"] },
  { name: "Angrezi Medium", year: 2020, genres: ["Comedy", "Drama"] },
  { name: "Thappad", year: 2020, genres: ["Drama"] },
  { name: "Lootcase", year: 2020, genres: ["Comedy", "Crime"] },
  { name: "Gunjan Saxena", year: 2020, genres: ["Biographical", "Drama", "War"] },
  { name: "Sadak 2", year: 2020, genres: ["Thriller", "Drama"] },
  { name: "Coolie No. 1", year: 2020, genres: ["Comedy"] },
  { name: "Indoo Ki Jawani", year: 2020, genres: ["Comedy", "Romance"] },
  { name: "Shakuntala Devi", year: 2020, genres: ["Biographical", "Drama"] },
  { name: "Dil Bechara", year: 2020, genres: ["Romance", "Drama"] },
  { name: "Laxmii", year: 2020, genres: ["Horror", "Comedy"] },
  { name: "Atrangi Re", year: 2021, genres: ["Romance", "Drama", "Musical"] },
  { name: "Shershaah", year: 2021, genres: ["Biographical", "War", "Drama"] },
  { name: "Sardar Udham", year: 2021, genres: ["Biographical", "Historical", "Drama"] },
  { name: "Sooryavanshi", year: 2021, genres: ["Action", "Thriller"] },
  { name: "Antim: The Final Truth", year: 2021, genres: ["Action", "Crime", "Drama"] },
  { name: "Bunty Aur Babli 2", year: 2021, genres: ["Comedy", "Action", "Crime"] },
  { name: "Satyameva Jayate 2", year: 2021, genres: ["Action", "Thriller"] },
  { name: "83", year: 2021, genres: ["Sports", "Drama", "Biographical"] },
  { name: "Pushpa: The Rise", year: 2021, genres: ["Action", "Crime", "Drama"] },
  { name: "Radhe", year: 2021, genres: ["Action", "Thriller"] },
  { name: "Bhool Bhulaiyaa 2", year: 2022, genres: ["Horror", "Comedy", "Thriller"] },
  { name: "Kashmir Files", year: 2022, genres: ["Drama", "Thriller"] },
  { name: "Gangubai Kathiawadi", year: 2022, genres: ["Biographical", "Drama"] },
  { name: "Bachchhan Paandey", year: 2022, genres: ["Action", "Comedy"] },
  { name: "RRR", year: 2022, genres: ["Action", "Drama", "Epic"] },
  { name: "KGF: Chapter 2", year: 2022, genres: ["Action", "Crime", "Thriller"] },
  { name: "Heropanti 2", year: 2022, genres: ["Action", "Thriller"] },
  { name: "Runway 34", year: 2022, genres: ["Thriller", "Drama"] },
  { name: "Dhaakad", year: 2022, genres: ["Action", "Thriller"] },
  { name: "Samrat Prithviraj", year: 2022, genres: ["Action", "Historical", "Drama"] },
  { name: "Vikram", year: 2022, genres: ["Action", "Thriller"] },
  { name: "Brahmastra", year: 2022, genres: ["Action", "Fantasy", "Adventure"] },
  { name: "Vikram Vedha", year: 2022, genres: ["Action", "Crime", "Thriller"] },
  { name: "Ram Setu", year: 2022, genres: ["Action", "Adventure", "Mystery"] },
  { name: "Drishyam 2", year: 2022, genres: ["Thriller", "Crime", "Drama"] },
  { name: "Cirkus", year: 2022, genres: ["Comedy"] },
  { name: "Pathaan", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Tu Jhoothi Main Makkaar", year: 2023, genres: ["Romance", "Comedy"] },
  { name: "Bholaa", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Kisi Ka Bhai Kisi Ki Jaan", year: 2023, genres: ["Action", "Comedy", "Drama"] },
  { name: "The Kerala Story", year: 2023, genres: ["Drama"] },
  { name: "Zara Hatke Zara Bachke", year: 2023, genres: ["Romance", "Comedy"] },
  { name: "Adipurush", year: 2023, genres: ["Action", "Fantasy", "Epic"] },
  { name: "Satyaprem Ki Katha", year: 2023, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Rocky Aur Rani Kii Prem Kahaani", year: 2023, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Gadar 2", year: 2023, genres: ["Action", "Drama", "Historical"] },
  { name: "OMG 2", year: 2023, genres: ["Comedy", "Drama"] },
  { name: "Dream Girl 2", year: 2023, genres: ["Comedy", "Romance"] },
  { name: "Jawan", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Fukrey 3", year: 2023, genres: ["Comedy"] },
  { name: "Mission Raniganj", year: 2023, genres: ["Biographical", "Drama", "Thriller"] },
  { name: "Ganpath", year: 2023, genres: ["Action", "Sci-Fi"] },
  { name: "Tiger 3", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Animal", year: 2023, genres: ["Action", "Crime", "Drama"] },
  { name: "Sam Bahadur", year: 2023, genres: ["Biographical", "War", "Drama"] },
  { name: "Dunki", year: 2023, genres: ["Comedy", "Drama"] },
  { name: "Salaar", year: 2023, genres: ["Action", "Thriller"] },
  { name: "Amar Singh Chamkila", year: 2024, genres: ["Biographical", "Musical", "Drama"] },
  { name: "Crew", year: 2024, genres: ["Comedy", "Crime"] },
  { name: "Bade Miyan Chote Miyan", year: 2024, genres: ["Action", "Comedy"] },
  { name: "Maidaan", year: 2024, genres: ["Sports", "Biographical", "Drama"] },
  { name: "Chandu Champion", year: 2024, genres: ["Biographical", "Sports", "Drama"] },
  { name: "Kalki 2898 AD", year: 2024, genres: ["Sci-Fi", "Action", "Fantasy"] },
  { name: "Singham Again", year: 2024, genres: ["Action", "Thriller"] },
  { name: "Stree 2", year: 2024, genres: ["Horror", "Comedy"] },
  { name: "Welcome To The Jungle", year: 2024, genres: ["Comedy", "Adventure"] },
  { name: "Fighter", year: 2024, genres: ["Action", "Drama", "War"] },
  { name: "Teri Baaton Mein Aisa Uljha Jiya", year: 2024, genres: ["Romance", "Comedy", "Sci-Fi"] },
  { name: "Shaitaan", year: 2024, genres: ["Horror", "Thriller"] },
  { name: "Article 370", year: 2024, genres: ["Action", "Thriller", "Political"] },
  { name: "Yodha", year: 2024, genres: ["Action", "Thriller"] },
  { name: "Bastar: The Naxal Story", year: 2024, genres: ["Action", "Thriller", "Political"] },
  { name: "Swatantrya Veer Savarkar", year: 2024, genres: ["Biographical", "Historical", "Drama"] },
  { name: "Madgaon Express", year: 2024, genres: ["Comedy"] },
  { name: "Ruslaan", year: 2024, genres: ["Action", "Thriller"] },
  { name: "Srikanth", year: 2024, genres: ["Biographical", "Drama"] },
  { name: "Mr. & Mrs. Mahi", year: 2024, genres: ["Romance", "Sports", "Drama"] },
  { name: "Munjya", year: 2024, genres: ["Horror", "Comedy"] },
  { name: "Ishq Vishk Rebound", year: 2024, genres: ["Romance", "Comedy"] },
  { name: "Kill", year: 2024, genres: ["Action", "Thriller"] },
  { name: "Sarfira", year: 2024, genres: ["Drama", "Biographical"] },
  { name: "Bad Newz", year: 2024, genres: ["Comedy", "Drama"] },
  { name: "Khel Khel Mein", year: 2024, genres: ["Comedy", "Drama"] },
  { name: "Do Aur Do Pyaar", year: 2024, genres: ["Romance", "Comedy", "Drama"] }
];





