// Bollywood movies data with release date and genre
export const bollywoodMovies = [
  { name: "Dilwale Dulhania Le Jayenge", year: 1995, genres: ["Romance", "Drama", "Comedy"] },
  { name: "3 Idiots", year: 2009, genres: ["Comedy", "Drama"] },
  { name: "Lagaan", year: 2001, genres: ["Drama", "Sports", "Musical"] },
  { name: "Sholay", year: 1975, genres: ["Action", "Adventure", "Drama"] },
  { name: "Dangal", year: 2016, genres: ["Biographical", "Sports", "Drama"] },
  { name: "PK", year: 2014, genres: ["Comedy", "Drama", "Sci-Fi"] },
  { name: "Bajrangi Bhaijaan", year: 2015, genres: ["Action", "Comedy", "Drama"] },
  { name: "Sultan", year: 2016, genres: ["Sports", "Action", "Drama"] },
  { name: "Padmaavat", year: 2018, genres: ["Drama", "Historical", "Epic"] },
  { name: "Sanju", year: 2018, genres: ["Biographical", "Drama"] },
  { name: "Tiger Zinda Hai", year: 2017, genres: ["Action", "Thriller"] },
  { name: "War", year: 2019, genres: ["Action", "Thriller"] },
  { name: "Kabir Singh", year: 2019, genres: ["Romance", "Drama"] },
  { name: "Good Newwz", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Tanhaji", year: 2020, genres: ["Action", "Historical", "Drama"] },
  { name: "Baaghi 3", year: 2020, genres: ["Action", "Thriller"] },
  { name: "Bahubali 2: The Conclusion", year: 2017, genres: ["Action", "Drama", "Epic"] },
  { name: "Bahubali: The Beginning", year: 2015, genres: ["Action", "Drama", "Epic"] },
  { name: "Queen", year: 2013, genres: ["Comedy", "Drama"] },
  { name: "Zindagi Na Milegi Dobara", year: 2011, genres: ["Comedy", "Drama"] },
  { name: "Yeh Jawaani Hai Deewani", year: 2013, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Barfi!", year: 2012, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Gully Boy", year: 2019, genres: ["Musical", "Drama"] },
  { name: "Andhadhun", year: 2018, genres: ["Thriller", "Comedy", "Crime"] },
  { name: "Stree", year: 2018, genres: ["Horror", "Comedy"] },
  { name: "Badhaai Ho", year: 2018, genres: ["Comedy", "Drama"] },
  { name: "Uri: The Surgical Strike", year: 2019, genres: ["Action", "War", "Drama"] },
  { name: "Kesari", year: 2019, genres: ["Action", "War", "Historical"] },
  { name: "Chhichhore", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Dream Girl", year: 2019, genres: ["Comedy", "Romance"] },
  { name: "Housefull 4", year: 2019, genres: ["Comedy"] },
  { name: "Total Dhamaal", year: 2019, genres: ["Comedy", "Adventure"] },
  { name: "Mission Mangal", year: 2019, genres: ["Drama", "Sci-Fi"] },
  { name: "Saaho", year: 2019, genres: ["Action", "Thriller"] },
  { name: "Bharat", year: 2019, genres: ["Drama", "Action"] },
  { name: "Super 30", year: 2019, genres: ["Biographical", "Drama"] },
  { name: "The Sky Is Pink", year: 2019, genres: ["Biographical", "Drama"] },
  { name: "Made in China", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Ujda Chaman", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Bala", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Marjaavaan", year: 2019, genres: ["Action", "Romance", "Drama"] },
  { name: "Pati Patni Aur Woh", year: 2019, genres: ["Comedy", "Romance"] },
  { name: "Street Dancer 3D", year: 2020, genres: ["Musical", "Dance", "Drama"] },
  { name: "Panga", year: 2020, genres: ["Sports", "Drama"] },
  { name: "Malang", year: 2020, genres: ["Action", "Thriller", "Romance"] },
  { name: "Shubh Mangal Zyada Saavdhan", year: 2020, genres: ["Comedy", "Romance"] },
  { name: "Angrezi Medium", year: 2020, genres: ["Comedy", "Drama"] },
  { name: "Thappad", year: 2020, genres: ["Drama"] },
  { name: "Lootcase", year: 2020, genres: ["Comedy", "Crime"] },
  { name: "Gunjan Saxena", year: 2020, genres: ["Biographical", "Drama", "War"] },
  { name: "Sadak 2", year: 2020, genres: ["Thriller", "Drama"] },
  { name: "Coolie No. 1", year: 2020, genres: ["Comedy"] },
  { name: "Indoo Ki Jawani", year: 2020, genres: ["Comedy", "Romance"] },
  { name: "Shakuntala Devi", year: 2020, genres: ["Biographical", "Drama"] },
  { name: "Dil Bechara", year: 2020, genres: ["Romance", "Drama"] },
  { name: "Laxmii", year: 2020, genres: ["Horror", "Comedy"] },
  { name: "Amar Prem", year: 1972, genres: ["Romance", "Drama"] },
  { name: "Deewaar", year: 1975, genres: ["Action", "Crime", "Drama"] },
  { name: "Zanjeer", year: 1973, genres: ["Action", "Crime", "Drama"] },
  { name: "Don", year: 1978, genres: ["Action", "Crime", "Thriller"] },
  { name: "Trishul", year: 1978, genres: ["Action", "Drama"] },
  { name: "Kaala Patthar", year: 1979, genres: ["Drama"] },
  { name: "Mr. India", year: 1987, genres: ["Sci-Fi", "Comedy", "Action"] },
  { name: "Qayamat Se Qayamat Tak", year: 1988, genres: ["Romance", "Musical", "Drama"] },
  { name: "Maine Pyar Kiya", year: 1989, genres: ["Romance", "Musical", "Drama"] },
  { name: "Hum Aapke Hain Koun..!", year: 1994, genres: ["Romance", "Musical", "Drama"] },
  { name: "Kuch Kuch Hota Hai", year: 1998, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Mohabbatein", year: 2000, genres: ["Romance", "Musical", "Drama"] },
  { name: "Kabhi Khushi Kabhie Gham", year: 2001, genres: ["Romance", "Drama", "Musical"] },
  { name: "Kal Ho Naa Ho", year: 2003, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Veer-Zaara", year: 2004, genres: ["Romance", "Drama", "Musical"] },
  { name: "Swades", year: 2004, genres: ["Drama"] },
  { name: "Black", year: 2005, genres: ["Drama"] },
  { name: "Rang De Basanti", year: 2006, genres: ["Drama", "Comedy"] },
  { name: "Chak De! India", year: 2007, genres: ["Sports", "Drama"] },
  { name: "Taare Zameen Par", year: 2007, genres: ["Drama", "Family"] },
  { name: "Jodhaa Akbar", year: 2008, genres: ["Romance", "Historical", "Drama"] },
  { name: "Ghajini", year: 2008, genres: ["Action", "Thriller", "Romance"] },
  { name: "Wake Up Sid", year: 2009, genres: ["Romance", "Comedy", "Drama"] },
  { name: "My Name Is Khan", year: 2010, genres: ["Drama"] },
  { name: "Once Upon a Time in Mumbai", year: 2010, genres: ["Crime", "Drama"] },
  { name: "Band Baaja Baaraat", year: 2010, genres: ["Romance", "Comedy"] },
  { name: "Don 2", year: 2011, genres: ["Action", "Crime", "Thriller"] },
  { name: "Ra.One", year: 2011, genres: ["Action", "Sci-Fi", "Superhero"] },
  { name: "Agneepath", year: 2012, genres: ["Action", "Crime", "Drama"] },
  { name: "Ek Tha Tiger", year: 2012, genres: ["Action", "Romance", "Thriller"] },
  { name: "Jab Tak Hai Jaan", year: 2012, genres: ["Romance", "Drama"] },
  { name: "Chennai Express", year: 2013, genres: ["Action", "Comedy", "Romance"] },
  { name: "Krrish 3", year: 2013, genres: ["Action", "Sci-Fi", "Superhero"] },
  { name: "Dhoom 3", year: 2013, genres: ["Action", "Crime", "Thriller"] },
  { name: "Happy New Year", year: 2014, genres: ["Action", "Comedy", "Heist"] },
  { name: "Kick", year: 2014, genres: ["Action", "Comedy", "Thriller"] },
  { name: "Haider", year: 2014, genres: ["Drama", "Thriller"] },
  { name: "2 States", year: 2014, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Bang Bang!", year: 2014, genres: ["Action", "Romance", "Thriller"] },
  { name: "Happy Ending", year: 2014, genres: ["Romance", "Comedy"] },
  { name: "Roy", year: 2015, genres: ["Romance", "Thriller", "Drama"] },
  { name: "Dilwale", year: 2015, genres: ["Action", "Comedy", "Romance"] },
  { name: "Tamasha", year: 2015, genres: ["Romance", "Drama"] },
  { name: "Airlift", year: 2016, genres: ["Drama", "Thriller"] },
  { name: "Rustom", year: 2016, genres: ["Thriller", "Drama"] },
  { name: "Ae Dil Hai Mushkil", year: 2016, genres: ["Romance", "Musical", "Drama"] },
  { name: "Dear Zindagi", year: 2016, genres: ["Drama", "Romance"] },
  { name: "Raees", year: 2017, genres: ["Action", "Crime", "Drama"] },
  { name: "Toilet: Ek Prem Katha", year: 2017, genres: ["Comedy", "Drama"] },
  { name: "Judwaa 2", year: 2017, genres: ["Comedy", "Action"] },
  { name: "Golmaal Again", year: 2017, genres: ["Comedy", "Horror"] },
  { name: "Pad Man", year: 2018, genres: ["Biographical", "Drama", "Comedy"] },
  { name: "Raazi", year: 2018, genres: ["Spy", "Thriller", "Drama"] },
  { name: "Simmba", year: 2018, genres: ["Action", "Comedy", "Crime"] },
  { name: "Zero", year: 2018, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Thugs of Hindostan", year: 2018, genres: ["Action", "Adventure", "Drama"] },
  { name: "2.0", year: 2018, genres: ["Action", "Sci-Fi", "Thriller"] },
  { name: "Kedarnath", year: 2018, genres: ["Romance", "Drama"] },
  { name: "Manikarnika", year: 2019, genres: ["Biographical", "Historical", "Drama"] },
  { name: "Kalank", year: 2019, genres: ["Romance", "Drama", "Musical"] },
  { name: "Student of the Year 2", year: 2019, genres: ["Romance", "Comedy", "Drama"] },
  { name: "India's Most Wanted", year: 2019, genres: ["Action", "Thriller"] },
  { name: "Article 15", year: 2019, genres: ["Crime", "Drama", "Thriller"] },
  { name: "Batla House", year: 2019, genres: ["Action", "Thriller", "Drama"] },
  { name: "Saand Ki Aankh", year: 2019, genres: ["Biographical", "Drama"] },
  { name: "Made in Heaven", year: 2019, genres: ["Drama"] },
  { name: "The Zoya Factor", year: 2019, genres: ["Romance", "Comedy"] },
  { name: "Prassthanam", year: 2019, genres: ["Action", "Crime", "Drama"] },
  { name: "Section 375", year: 2019, genres: ["Crime", "Drama", "Thriller"] },
  { name: "Laal Kaptaan", year: 2019, genres: ["Action", "Drama", "Western"] },
  { name: "Ujda Chaman", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Bala", year: 2019, genres: ["Comedy", "Drama"] },
  { name: "Pati Patni Aur Woh", year: 2019, genres: ["Comedy", "Romance"] },
  { name: "Dabangg 3", year: 2019, genres: ["Action", "Comedy", "Crime"] },
  { name: "Jab We Met", year: 2007, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Student of the Year", year: 2012, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Om Shanti Om", year: 2007, genres: ["Romance", "Drama", "Musical"] },
  { name: "Devdas", year: 2002, genres: ["Romance", "Drama", "Musical"] },
  { name: "Dil Chahta Hai", year: 2001, genres: ["Comedy", "Drama", "Romance"] },
  { name: "Dostana", year: 2008, genres: ["Comedy", "Romance"] },
  { name: "Rab Ne Bana Di Jodi", year: 2008, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Gangs of Wasseypur", year: 2012, genres: ["Action", "Crime", "Drama"] },
  { name: "Bhaag Milkha Bhaag", year: 2013, genres: ["Biographical", "Sports", "Drama"] },
  { name: "Mary Kom", year: 2014, genres: ["Biographical", "Sports", "Drama"] },
  { name: "Bajirao Mastani", year: 2015, genres: ["Romance", "Historical", "Drama"] },
  { name: "Dil Dhadakne Do", year: 2015, genres: ["Comedy", "Drama"] },
  { name: "Kapoor & Sons", year: 2016, genres: ["Comedy", "Drama"] },
  { name: "Badrinath Ki Dulhania", year: 2017, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Half Girlfriend", year: 2017, genres: ["Romance", "Drama"] },
  { name: "Ishqiya", year: 2010, genres: ["Crime", "Comedy", "Drama"] },
  { name: "Dabangg", year: 2010, genres: ["Action", "Comedy", "Crime"] },
  { name: "Dabangg 2", year: 2012, genres: ["Action", "Comedy", "Crime"] },
  { name: "Rowdy Rathore", year: 2012, genres: ["Action", "Comedy"] },
  { name: "Goliyon Ki Raasleela Ram-Leela", year: 2013, genres: ["Romance", "Action", "Drama"] },
  { name: "Khoobsurat", year: 2014, genres: ["Romance", "Comedy"] },
  { name: "Finding Fanny", year: 2014, genres: ["Comedy", "Drama", "Adventure"] },
  { name: "Bombay Velvet", year: 2015, genres: ["Crime", "Drama", "Thriller"] },
  { name: "Piku", year: 2015, genres: ["Comedy", "Drama"] },
  { name: "Prem Ratan Dhan Payo", year: 2015, genres: ["Romance", "Drama", "Musical"] },
  { name: "Fan", year: 2016, genres: ["Action", "Thriller", "Drama"] },
  { name: "M.S. Dhoni: The Untold Story", year: 2016, genres: ["Biographical", "Sports", "Drama"] },
  { name: "Kaabil", year: 2017, genres: ["Action", "Romance", "Thriller"] },
  { name: "Tubelight", year: 2017, genres: ["Drama", "War"] },
  { name: "Mubarakan", year: 2017, genres: ["Comedy", "Romance"] },
  { name: "Bareilly Ki Barfi", year: 2017, genres: ["Romance", "Comedy"] },
  { name: "Shubh Mangal Saavdhan", year: 2017, genres: ["Comedy", "Romance"] },
  { name: "Tumhari Sulu", year: 2017, genres: ["Comedy", "Drama"] },
  { name: "Fukrey", year: 2013, genres: ["Comedy"] },
  { name: "Fukrey Returns", year: 2017, genres: ["Comedy"] },
  { name: "Hindi Medium", year: 2017, genres: ["Comedy", "Drama"] },
  { name: "Newton", year: 2017, genres: ["Comedy", "Drama"] },
  { name: "Secret Superstar", year: 2017, genres: ["Musical", "Drama"] },
  { name: "Baaghi 2", year: 2018, genres: ["Action", "Thriller"] },
  { name: "Race 3", year: 2018, genres: ["Action", "Thriller", "Crime"] },
  { name: "Gold", year: 2018, genres: ["Sports", "Drama", "Historical"] },
  { name: "Satyameva Jayate", year: 2018, genres: ["Action", "Thriller"] },
  { name: "Sui Dhaaga", year: 2018, genres: ["Comedy", "Drama"] },
  { name: "Luka Chuppi", year: 2019, genres: ["Comedy", "Romance"] },
  { name: "De De Pyaar De", year: 2019, genres: ["Comedy", "Romance"] },
  { name: "Golmaal: Fun Unlimited", year: 2006, genres: ["Comedy"] },
  { name: "Golmaal Returns", year: 2008, genres: ["Comedy"] },
  { name: "Golmaal 3", year: 2010, genres: ["Comedy"] },
  { name: "Hera Pheri", year: 2000, genres: ["Comedy", "Crime"] },
  { name: "Phir Hera Pheri", year: 2006, genres: ["Comedy", "Crime"] },
  { name: "Munna Bhai M.B.B.S.", year: 2003, genres: ["Comedy", "Drama"] },
  { name: "Lage Raho Munna Bhai", year: 2006, genres: ["Comedy", "Drama"] },
  { name: "Welcome", year: 2007, genres: ["Comedy", "Action"] },
  { name: "Welcome Back", year: 2015, genres: ["Comedy", "Action"] },
  { name: "Singham", year: 2011, genres: ["Action", "Drama"] },
  { name: "Singham Returns", year: 2014, genres: ["Action", "Drama"] },
  { name: "Dhoom", year: 2004, genres: ["Action", "Crime", "Thriller"] },
  { name: "Dhoom 2", year: 2006, genres: ["Action", "Crime", "Thriller"] },
  { name: "Race", year: 2008, genres: ["Action", "Thriller", "Crime"] },
  { name: "Race 2", year: 2013, genres: ["Action", "Thriller", "Crime"] },
  { name: "Housefull", year: 2010, genres: ["Comedy"] },
  { name: "Housefull 2", year: 2012, genres: ["Comedy"] },
  { name: "Housefull 3", year: 2016, genres: ["Comedy"] },
  { name: "Drishyam", year: 2015, genres: ["Thriller", "Crime", "Drama"] },
  { name: "Tanu Weds Manu", year: 2011, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Tanu Weds Manu Returns", year: 2015, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Cocktail", year: 2012, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Rock On!!", year: 2008, genres: ["Musical", "Drama"] },
  { name: "Vicky Donor", year: 2012, genres: ["Comedy", "Romance"] },
  { name: "Delhi Belly", year: 2011, genres: ["Comedy", "Crime"] },
  { name: "Special 26", year: 2013, genres: ["Thriller", "Crime", "Drama"] },
  { name: "Baby", year: 2015, genres: ["Action", "Thriller"] },
  { name: "Neerja", year: 2016, genres: ["Biographical", "Thriller", "Drama"] },
  { name: "Pink", year: 2016, genres: ["Drama", "Thriller"] },
  { name: "Tumbbad", year: 2018, genres: ["Horror", "Drama", "Fantasy"] },
  { name: "Badla", year: 2019, genres: ["Thriller", "Mystery", "Drama"] },
  { name: "Sonu Ke Titu Ki Sweety", year: 2018, genres: ["Comedy", "Romance"] },
  { name: "Krrish", year: 2006, genres: ["Action", "Sci-Fi", "Superhero"] },
  { name: "Soorma", year: 2018, genres: ["Biographical", "Sports", "Drama"] },
  { name: "Lootera", year: 2013, genres: ["Romance", "Drama"] },
  { name: "Udta Punjab", year: 2016, genres: ["Crime", "Drama"] },
  { name: "Dum Laga Ke Haisha", year: 2015, genres: ["Comedy", "Romance", "Drama"] },
  { name: "Shuddh Desi Romance", year: 2013, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Gangs of Wasseypur Part 2", year: 2012, genres: ["Action", "Crime", "Drama"] },
  { name: "Andaz Apna Apna", year: 1994, genres: ["Comedy"] },
  { name: "Jaane Bhi Do Yaaro", year: 1983, genres: ["Comedy", "Thriller"] },
  { name: "Masoom", year: 1983, genres: ["Drama", "Family"] },
  { name: "Aashiqui", year: 1990, genres: ["Romance", "Musical", "Drama"] },
  { name: "Dil", year: 1990, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Dil To Pagal Hai", year: 1997, genres: ["Romance", "Musical", "Drama"] },
  { name: "Hum Dil De Chuke Sanam", year: 1999, genres: ["Romance", "Drama", "Musical"] },
  { name: "Dil Se..", year: 1998, genres: ["Romance", "Thriller", "Drama"] },
  { name: "Sarfarosh", year: 1999, genres: ["Action", "Thriller", "Crime"] },
  { name: "The Lunchbox", year: 2013, genres: ["Drama", "Romance"] },
  { name: "Mimi", year: 2021, genres: ["Comedy", "Drama"] },
  { name: "Anand", year: 1971, genres: ["Drama"] },
  { name: "Saathiya", year: 2002, genres: ["Romance", "Drama", "Musical"] },
  { name: "Bunty Aur Babli", year: 2005, genres: ["Comedy", "Romance", "Crime"] },
  { name: "Salaam Namaste", year: 2005, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Fanaa", year: 2006, genres: ["Romance", "Thriller", "Drama"] },
  { name: "Guru", year: 2007, genres: ["Drama", "Biographical"] },
  { name: "Namastey London", year: 2007, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Singh Is Kinng", year: 2008, genres: ["Action", "Comedy"] },
  { name: "Love Aaj Kal", year: 2009, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Ajab Prem Ki Ghazab Kahani", year: 2009, genres: ["Romance", "Comedy"] },
  { name: "Rockstar", year: 2011, genres: ["Musical", "Romance", "Drama"] },
  { name: "Talaash", year: 2012, genres: ["Thriller", "Mystery", "Drama"] },
  { name: "OMG: Oh My God!", year: 2012, genres: ["Comedy", "Drama"] },
  { name: "Kahaani", year: 2012, genres: ["Thriller", "Mystery", "Drama"] },
  { name: "Raanjhanaa", year: 2013, genres: ["Romance", "Drama"] },
  { name: "Kaho Naa... Pyaar Hai", year: 2000, genres: ["Romance", "Thriller", "Musical"] },
  { name: "Taal", year: 1999, genres: ["Romance", "Musical", "Drama"] },
  { name: "English Vinglish", year: 2012, genres: ["Comedy", "Drama"] },
  { name: "Kai Po Che!", year: 2013, genres: ["Drama", "Sports"] },
  { name: "Highway", year: 2014, genres: ["Drama", "Romance"] },
  { name: "Masaan", year: 2015, genres: ["Drama", "Romance"] },
  { name: "Khosla Ka Ghosla!", year: 2006, genres: ["Comedy", "Drama"] },
  { name: "Udaan", year: 2010, genres: ["Drama"] },
  { name: "A Wednesday!", year: 2008, genres: ["Thriller", "Drama"] },
  { name: "October", year: 2018, genres: ["Drama", "Romance"] },
  { name: "Trapped", year: 2016, genres: ["Thriller", "Drama"] },
  { name: "Lipstick Under My Burkha", year: 2017, genres: ["Drama", "Comedy"] },
  { name: "Jolly LLB", year: 2013, genres: ["Comedy", "Drama"] },
  { name: "Jolly LLB 2", year: 2017, genres: ["Comedy", "Drama"] },
  { name: "Wanted", year: 2009, genres: ["Action", "Crime", "Thriller"] },
  { name: "Jab Harry Met Sejal", year: 2017, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Raajneeti", year: 2010, genres: ["Political", "Thriller", "Drama"] },
  { name: "Main Hoon Na", year: 2004, genres: ["Action", "Comedy", "Drama"] },
  { name: "Jai Ho", year: 2014, genres: ["Action", "Drama"] },
  { name: "Maine Pyaar Kyun Kiya", year: 2005, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Partner", year: 2007, genres: ["Comedy", "Romance"] },
  { name: "Koi... Mil Gaya", year: 2003, genres: ["Sci-Fi", "Drama", "Musical"] },
  { name: "No Problem", year: 2010, genres: ["Comedy", "Action"] },
  { name: "No Entry", year: 2005, genres: ["Comedy"] },
  { name: "R... Rajkumar", year: 2013, genres: ["Action", "Romance", "Comedy"] },
  { name: "Hero", year: 2015, genres: ["Action", "Romance", "Drama"] },
  { name: "Heropanti", year: 2014, genres: ["Action", "Romance"] },
  { name: "Kismat Konnection", year: 2008, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Chup Chup Ke", year: 2006, genres: ["Comedy", "Drama"] },
  { name: "Ready", year: 2011, genres: ["Comedy", "Action"] },
  { name: "Laila Majnu", year: 2018, genres: ["Romance", "Drama"] },
  { name: "Bhootnath", year: 2008, genres: ["Comedy", "Fantasy", "Family"] },
  { name: "Bhootnath Returns", year: 2014, genres: ["Comedy", "Fantasy", "Drama"] },
  { name: "Bhool Bhulaiyaa", year: 2007, genres: ["Horror", "Comedy", "Thriller"] },
  { name: "Humpty Sharma Ki Dulhania", year: 2014, genres: ["Romance", "Comedy", "Drama"] },
  { name: "Kidnap", year: 2008, genres: ["Action", "Thriller", "Drama"] },
  { name: "Dhadak", year: 2018, genres: ["Romance", "Drama"] }
];
